### PR TITLE
* Add failing test for using surround

### PR DESCRIPTION
**Pull request by PikachuEXE**
I don't even know how to make existing tests pass...

### CODE REVIEW

**Comment by k0kubun** [comment]
Thanks, I'll check that later.

**Comment by k0kubun** [comment]
@PikachuEXE I'm not sure how cells works, but I fixed your test in https://github.com/hamlit/cells-hamlit2/commit/ea0f8b3ab21acb6174faeaf77bb5b1cf8234591e and released it as v0.2.0. Please try it.

cc: @willnet

**Comment by PikachuEXE** [comment]
On holiday
Will try next week

**Comment by PikachuEXE** [comment]
`0.2.0` is working well with `surround`. Thanks!

**Pull request merged**
